version: '3'
services:
  spark:
    # image: docker-hadoop-spark
    image: cyborgcat/docker-hadoop-spark:1.0.0
    container_name: hadoop-node
    ports:
    - 8088:8088
    - 8042:8042
    - 4040:4040 
    - 50070:50070
    - 9000:9000
    # volumes:
      # - $PWD/data:/data
    links:
    - db
    # entrypoint: ["/etc/bootstrap.sh"]
    tty: true
    stdin_open: true
    command: ["bash"]
  db:
    image: postgres
    container_name: postgres-node
    environment:
      POSTGRES_PASSWORD: PASSWORD
    # volumes:
    # - .:/tmp
    expose:
    - 5432
